services:
  mysql:
    image: mysql:8.0
    container_name: servico-vendas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: servico_vendas
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - vendas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  servico-vendas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servico-vendas-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=servico_vendas
      - JWT_SECRET=jwt_secret_production_123
      - SERVICO_PRINCIPAL_URL=http://servico-principal:3000
      - CORS_ORIGIN=*
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - CRONJOB_INTERVAL_SECONDS=10
      - EXTERNAL_WEBHOOK_URL=http://localhost:3000/api/webhook/pagamento
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - vendas-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  vendas-network:
    driver: bridge
